// Country list organized by first letter for alphabet navigation
export const COUNTRIES_BY_LETTER = {
  A: [
    { name: 'Afghanistan', code: 'AF' },
    { name: 'Ägypten', code: 'EG' },
    { name: 'Albanien', code: 'AL' },
    { name: 'Algerien', code: 'DZ' },
    { name: 'Andorra', code: 'AD' },
    { name: 'Angola', code: 'AO' },
    { name: 'Argentinien', code: 'AR' },
    { name: 'Armenien', code: 'AM' },
    { name: 'Aserbaidschan', code: 'AZ' },
    { name: 'Äthiopien', code: 'ET' },
    { name: 'Australien', code: 'AU' },
    { name: 'Österreich', code: 'AT' },
  ],
  B: [
    { name: 'Bahamas', code: 'BS' },
    { name: 'Bahrain', code: 'BH' },
    { name: 'Bangladesch', code: 'BD' },
    { name: 'Barbados', code: 'BB' },
    { name: 'Belgien', code: 'BE' },
    { name: 'Belize', code: 'BZ' },
    { name: 'Benin', code: 'BJ' },
    { name: 'Bhutan', code: 'BT' },
    { name: 'Bolivien', code: 'BO' },
    { name: 'Bosnien und Herzegowina', code: 'BA' },
    { name: 'Botswana', code: 'BW' },
    { name: 'Brasilien', code: 'BR' },
    { name: 'Brunei', code: 'BN' },
    { name: 'Bulgarien', code: 'BG' },
    { name: 'Burkina Faso', code: 'BF' },
    { name: 'Burundi', code: 'BI' },
  ],
  C: [
    { name: 'Chile', code: 'CL' },
    { name: 'China', code: 'CN' },
    { name: 'Costa Rica', code: 'CR' },
  ],
  D: [
    { name: 'Dänemark', code: 'DK' },
    { name: 'Dominica', code: 'DM' },
    { name: 'Dominikanische Republik', code: 'DO' },
    { name: 'Dschibuti', code: 'DJ' },
  ],
  E: [
    { name: 'Ecuador', code: 'EC' },
    { name: 'El Salvador', code: 'SV' },
    { name: 'Elfenbeinküste', code: 'CI' },
    { name: 'Eritrea', code: 'ER' },
    { name: 'Estland', code: 'EE' },
  ],
  F: [
    { name: 'Fidschi', code: 'FJ' },
    { name: 'Finnland', code: 'FI' },
    { name: 'Frankreich', code: 'FR' },
  ],
  G: [
    { name: 'Gabun', code: 'GA' },
    { name: 'Gambia', code: 'GM' },
    { name: 'Georgien', code: 'GE' },
    { name: 'Ghana', code: 'GH' },
    { name: 'Grenada', code: 'GD' },
    { name: 'Griechenland', code: 'GR' },
    { name: 'Großbritannien', code: 'GB' },
    { name: 'Guatemala', code: 'GT' },
    { name: 'Guinea', code: 'GN' },
    { name: 'Guyana', code: 'GY' },
  ],
  H: [
    { name: 'Haiti', code: 'HT' },
    { name: 'Honduras', code: 'HN' },
  ],
  I: [
    { name: 'Indien', code: 'IN' },
    { name: 'Indonesien', code: 'ID' },
    { name: 'Irak', code: 'IQ' },
    { name: 'Iran', code: 'IR' },
    { name: 'Irland', code: 'IE' },
    { name: 'Island', code: 'IS' },
    { name: 'Israel', code: 'IL' },
    { name: 'Italien', code: 'IT' },
  ],
  J: [
    { name: 'Jamaika', code: 'JM' },
    { name: 'Japan', code: 'JP' },
    { name: 'Jemen', code: 'YE' },
    { name: 'Jordanien', code: 'JO' },
  ],
  K: [
    { name: 'Kambodscha', code: 'KH' },
    { name: 'Kamerun', code: 'CM' },
    { name: 'Kanada', code: 'CA' },
    { name: 'Kap Verde', code: 'CV' },
    { name: 'Kasachstan', code: 'KZ' },
    { name: 'Katar', code: 'QA' },
    { name: 'Kenia', code: 'KE' },
    { name: 'Kirgisistan', code: 'KG' },
    { name: 'Kolumbien', code: 'CO' },
    { name: 'Kongo', code: 'CG' },
    { name: 'Korea (Süd)', code: 'KR' },
    { name: 'Kosovo', code: 'XK' },
    { name: 'Kroatien', code: 'HR' },
    { name: 'Kuba', code: 'CU' },
    { name: 'Kuwait', code: 'KW' },
  ],
  L: [
    { name: 'Laos', code: 'LA' },
    { name: 'Lesotho', code: 'LS' },
    { name: 'Lettland', code: 'LV' },
    { name: 'Libanon', code: 'LB' },
    { name: 'Liberia', code: 'LR' },
    { name: 'Libyen', code: 'LY' },
    { name: 'Liechtenstein', code: 'LI' },
    { name: 'Litauen', code: 'LT' },
    { name: 'Luxemburg', code: 'LU' },
  ],
  M: [
    { name: 'Madagaskar', code: 'MG' },
    { name: 'Malawi', code: 'MW' },
    { name: 'Malaysia', code: 'MY' },
    { name: 'Malediven', code: 'MV' },
    { name: 'Mali', code: 'ML' },
    { name: 'Malta', code: 'MT' },
    { name: 'Marokko', code: 'MA' },
    { name: 'Mauritius', code: 'MU' },
    { name: 'Mexiko', code: 'MX' },
    { name: 'Moldau', code: 'MD' },
    { name: 'Monaco', code: 'MC' },
    { name: 'Mongolei', code: 'MN' },
    { name: 'Montenegro', code: 'ME' },
    { name: 'Mosambik', code: 'MZ' },
    { name: 'Myanmar', code: 'MM' },
  ],
  N: [
    { name: 'Namibia', code: 'NA' },
    { name: 'Nepal', code: 'NP' },
    { name: 'Neuseeland', code: 'NZ' },
    { name: 'Nicaragua', code: 'NI' },
    { name: 'Niederlande', code: 'NL' },
    { name: 'Niger', code: 'NE' },
    { name: 'Nigeria', code: 'NG' },
    { name: 'Nordmazedonien', code: 'MK' },
    { name: 'Norwegen', code: 'NO' },
  ],
  O: [
    { name: 'Oman', code: 'OM' },
    { name: 'Österreich', code: 'AT' },
  ],
  P: [
    { name: 'Pakistan', code: 'PK' },
    { name: 'Panama', code: 'PA' },
    { name: 'Papua-Neuguinea', code: 'PG' },
    { name: 'Paraguay', code: 'PY' },
    { name: 'Peru', code: 'PE' },
    { name: 'Philippinen', code: 'PH' },
    { name: 'Polen', code: 'PL' },
    { name: 'Portugal', code: 'PT' },
  ],
  Q: [
    { name: 'Katar', code: 'QA' },
  ],
  R: [
    { name: 'Rumänien', code: 'RO' },
    { name: 'Russland', code: 'RU' },
    { name: 'Ruanda', code: 'RW' },
  ],
  S: [
    { name: 'Saudi-Arabien', code: 'SA' },
    { name: 'Schweden', code: 'SE' },
    { name: 'Schweiz', code: 'CH' },
    { name: 'Senegal', code: 'SN' },
    { name: 'Serbien', code: 'RS' },
    { name: 'Singapur', code: 'SG' },
    { name: 'Slowakei', code: 'SK' },
    { name: 'Slowenien', code: 'SI' },
    { name: 'Somalia', code: 'SO' },
    { name: 'Spanien', code: 'ES' },
    { name: 'Sri Lanka', code: 'LK' },
    { name: 'Südafrika', code: 'ZA' },
    { name: 'Sudan', code: 'SD' },
    { name: 'Syrien', code: 'SY' },
  ],
  T: [
    { name: 'Tadschikistan', code: 'TJ' },
    { name: 'Taiwan', code: 'TW' },
    { name: 'Tansania', code: 'TZ' },
    { name: 'Thailand', code: 'TH' },
    { name: 'Togo', code: 'TG' },
    { name: 'Tschechien', code: 'CZ' },
    { name: 'Tunesien', code: 'TN' },
    { name: 'Türkei', code: 'TR' },
    { name: 'Turkmenistan', code: 'TM' },
  ],
  U: [
    { name: 'Uganda', code: 'UG' },
    { name: 'Ukraine', code: 'UA' },
    { name: 'Ungarn', code: 'HU' },
    { name: 'Uruguay', code: 'UY' },
    { name: 'USA', code: 'US' },
    { name: 'Usbekistan', code: 'UZ' },
  ],
  V: [
    { name: 'Venezuela', code: 'VE' },
    { name: 'Vereinigte Arabische Emirate', code: 'AE' },
    { name: 'Vietnam', code: 'VN' },
  ],
  W: [
    { name: 'Weißrussland', code: 'BY' },
  ],
  X: [],
  Y: [
    { name: 'Jemen', code: 'YE' },
  ],
  Z: [
    { name: 'Zypern', code: 'CY' },
  ],
};

export const DOCUMENT_TYPES = [
  'Führerschein',
  'Personalausweis',
  'Reisepass',
  'Aufenthaltstitel',
  'Visum',
  'Krankenkasse',
];

export const ALPHABET = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split('');
